[font]
size = 9.0

[font.bold]
family = "JetBrainsMono Nerd Font"
#size = 14
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
#size = 14
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
#size = 14
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
#size = 14
style = "Regular"

[window]
decorations = "none"
opacity = 0.8
